name: Tourism Project Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install -r tourism_project/requirements.txt

      - name: Verify Dataset Files
        run: |
          ls tourism_project/data

      - name: Verify Model File
        run: |
          ls tourism_project/model_building

      - name: Verify Deployment Files
        run: |
          ls tourism_project/deployment

      - name: Pipeline Validation
        run: |
          echo "Tourism MLOps Pipeline Executed Successfully"
