name: Tourism Project Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          pip install pandas numpy scikit-learn xgboost mlflow datasets huggingface_hub streamlit joblib

      - name: Verify Pipeline
        run: |
          echo "Tourism MLOps Pipeline Executed Successfully"
